In [1]:
import  numpy as np
import pandas as pd

# Pair Programming NumPy II

In [ ]:
# Seguimos trabajando con NumPy, en este caso practicaremos 
# como acceder a distintos elementos de nuestros arrays y como cambiar
#  su forma para poder hacer operaciones entre varios arrays.

# Cread un array de dos dimensiones de 5 filas y 3 columnas. 
# Sobre el array creado anteriormente, extraed:
# El valor de la primera fila y la segunda columna.
# Los valores de la segunda fila y las dos primeras columnas.
# Extraed las filas pares (incluyendo la 0) y todas las columnas.
# Extraed los valores que sean mayores que 0.5.
# Extraed los valores menores que 0.2 o mayores que 0.5

In [3]:
bidimensional = np.random.rand (5,3)
bidimensional

array([[0.95193536, 0.6341301 , 0.31405466],
       [0.2294092 , 0.12720547, 0.19661694],
       [0.50156404, 0.39985366, 0.917799  ],
       [0.65255853, 0.57362053, 0.33953027],
       [0.52854623, 0.81127364, 0.89057597]])

In [4]:
# El valor de la primera fila y la segunda columna.
bidimensional[0,1]

0.6341300964474743

In [5]:
# Los valores de la segunda fila y las dos primeras columnas.
bidimensional [1,:2]

array([0.2294092 , 0.12720547])

In [ ]:
# Extraed las filas pares (incluyendo la 0) y todas las columnas.
# Extraed los valores que sean mayores que 0.5.
# Extraed los valores menores que 0.2 o mayores que 0.5

In [7]:
bidimensional[::2,:]

array([[0.95193536, 0.6341301 , 0.31405466],
       [0.50156404, 0.39985366, 0.917799  ],
       [0.52854623, 0.81127364, 0.89057597]])

In [8]:
bidimensional[bidimensional>0.5]

array([0.95193536, 0.6341301 , 0.50156404, 0.917799  , 0.65255853,
       0.57362053, 0.52854623, 0.81127364, 0.89057597])

In [10]:
bidimensional [(bidimensional<0.2)|(bidimensional>0.5)]

array([0.95193536, 0.6341301 , 0.12720547, 0.19661694, 0.50156404,
       0.917799  , 0.65255853, 0.57362053, 0.52854623, 0.81127364,
       0.89057597])

In [ ]:
# Cread dos array de tres dimensiones:
# El primero de 2 matrices, 5 filas y 3 columnas.
# El segundo de 3 matrices, 2 filas y 5 columnas
# Haced un análisis exploratorio de los array creados. 
# Recordad que en el ejercicio de ayer nos creamos una función para esto.
# Sumad los dos arrays. ¿Podéis? ¿Por qué?
# Para cambiar la forma de un array y poder hacer operaciones 
# entre arrays que tienen distintas formas hemos aprendido dos métodos:
# .reshape()
# .transpose()
# Utiliza estas dos funciones para cambiar la forma de los array 
# y hacer operaciones entre ellos.

In [17]:
array1 = np.random.rand(2,5,3)
array2 = np.random.rand (3,2,5)

In [18]:
array1

array([[[0.05923446, 0.44887632, 0.37071892],
        [0.95918024, 0.92923549, 0.86201202],
        [0.92040091, 0.46296684, 0.91208168],
        [0.81623105, 0.3412751 , 0.14120406],
        [0.85247314, 0.70422144, 0.06217274]],

       [[0.29180658, 0.98929221, 0.55804771],
        [0.38364504, 0.11345103, 0.88549952],
        [0.71201993, 0.60240291, 0.19857557],
        [0.71606658, 0.87770765, 0.18420167],
        [0.95968162, 0.06548779, 0.42907327]]])

In [16]:
array2

array([[[0.12767029, 0.50538231, 0.05358565, 0.63950636, 0.36682524],
        [0.07414385, 0.26491172, 0.35797603, 0.64700667, 0.34451976]],

       [[0.77829446, 0.24999269, 0.26033385, 0.29826917, 0.03263032],
        [0.06156246, 0.235502  , 0.52187856, 0.0797551 , 0.77543694]],

       [[0.32857398, 0.69215718, 0.74494304, 0.9345175 , 0.76315222],
        [0.7113529 , 0.47380044, 0.98799668, 0.51514272, 0.10455885]]])

In [20]:
def propiedades(nuestro_array):
    print(f'La forma de nuestro array es', nuestro_array.shape)
    print(f'El tipo de nuestro array es', nuestro_array.dtype)
    print(f'El tamaño de nuestro array es', nuestro_array.size)
    print(f'Las dimensiones que tiene son', nuestro_array.ndim)

propiedades(array1)

La forma de nuestro array es (2, 5, 3)
El tipo de nuestro array es float64
El tamaño de nuestro array es 30
Las dimensiones que tiene son 3


In [21]:
propiedades (array2)

La forma de nuestro array es (3, 2, 5)
El tipo de nuestro array es float64
El tamaño de nuestro array es 30
Las dimensiones que tiene son 3


In [ ]:
# Haced un análisis exploratorio de los array creados. 
# Recordad que en el ejercicio de ayer nos creamos una función para esto.
# Sumad los dos arrays. ¿Podéis? ¿Por qué?

In [22]:
array1 + array2

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [ ]:
# no se pueden sumar porque como hemos visto tienen formas diferentes.

In [ ]:
# Para cambiar la forma de un array y poder hacer operaciones 
# entre arrays que tienen distintas formas hemos aprendido dos métodos:
# .reshape()
# .transpose()
# Utiliza estas dos funciones para cambiar la forma de los array 
# y hacer operaciones entre ellos.

In [23]:
array1

array([[[0.05923446, 0.44887632, 0.37071892],
        [0.95918024, 0.92923549, 0.86201202],
        [0.92040091, 0.46296684, 0.91208168],
        [0.81623105, 0.3412751 , 0.14120406],
        [0.85247314, 0.70422144, 0.06217274]],

       [[0.29180658, 0.98929221, 0.55804771],
        [0.38364504, 0.11345103, 0.88549952],
        [0.71201993, 0.60240291, 0.19857557],
        [0.71606658, 0.87770765, 0.18420167],
        [0.95968162, 0.06548779, 0.42907327]]])

In [24]:
array2

array([[[0.07397051, 0.96405513, 0.61987886, 0.50390385, 0.98483823],
        [0.67505384, 0.63777266, 0.91167652, 0.22777131, 0.85300749]],

       [[0.54987857, 0.68906152, 0.03418484, 0.31516168, 0.411174  ],
        [0.74998888, 0.16359266, 0.36683353, 0.01234933, 0.48859583]],

       [[0.90533875, 0.19396943, 0.10064451, 0.95288446, 0.13269776],
        [0.91036353, 0.94304471, 0.49990259, 0.75553714, 0.51680361]]])

In [25]:
array_traspo = np.transpose (array1,(1,2,0)) # que poner los indicies 

In [28]:
array_resha = np.reshape(array2, (5,3,2)) #con el numero 

In [29]:
array_traspo + array_resha

array([[[0.13320497, 1.25586171],
        [1.06875518, 1.49319606],
        [1.35555715, 1.23310156]],

       [[1.5969529 , 1.29532156],
        [1.1570068 , 0.96645852],
        [1.41189059, 1.57456105]],

       [[0.95458576, 1.02718161],
        [0.87414084, 1.35239179],
        [1.07567434, 0.56540911]],

       [[0.82858038, 1.20466241],
        [1.24661385, 1.07167708],
        [0.24184856, 1.13708613]],

       [[0.9851709 , 1.87004514],
        [1.64726615, 0.56539039],
        [0.81770989, 0.94587688]]])