In [ ]:

import numpy as np 

In [3]:
############################## Pair Programming NumPy IV ##############################

# Manos a la obra con la última lección de NumPy. 
# En este caso pondremos en práctica como generar arrays 
# que sigan ciertas distribuciones, así como las operaciones 
# de teoría de conjuntos básicas.

In [ ]:
# ¿Cómo podemos crear dos arrays de dos dimensiones usando 
# el método random_sample que tengan los mismos valores?

In [18]:
np.random.seed(42)

In [25]:
np.random.seed(42)
array1=np.random.random_sample((2,5))
array1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258]])

In [26]:
np.random.seed(42)
array2=np.random.random_sample((2,4))
array2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615]])

In [27]:
#Cread los siguientes arrays:
# Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, 
# con números entre 0 y 10, que no tengan decimales 
# y extrae sus valores únicos almacenándolos en una variable.

array3=np.random.randint(0,10,(2,3,5))
array3

array([[[3, 7, 7, 2, 5],
        [4, 1, 7, 5, 1],
        [4, 0, 9, 5, 8]],

       [[0, 9, 2, 6, 3],
        [8, 2, 4, 2, 6],
        [4, 8, 6, 1, 3]]])

In [28]:
array4=np.random.randint(0,10,(2,3,5))
array4

array([[[8, 1, 9, 8, 9],
        [4, 1, 3, 6, 7],
        [2, 0, 3, 1, 7]],

       [[3, 1, 5, 5, 9],
        [3, 5, 1, 9, 1],
        [9, 3, 7, 6, 8]]])

In [31]:
valores_unicos1=np.unique(array4)
valores_unicos1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:

# Un array de tres dimensiones con distribución binomial de 2 x 3 x 5,
#  con probabilidad de 0.3 y número de pruebas igual a 10. 
# Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

array5=np.random.binomial(10,0.3,size=(2,3,5))
array5

array([[[6, 4, 4, 3, 3],
        [6, 3, 2, 2, 2],
        [0, 3, 3, 2, 0]],

       [[2, 4, 4, 3, 5],
        [4, 5, 5, 3, 1],
        [2, 4, 4, 3, 2]]])

In [30]:
valores_unicos2=np.unique(array5)
valores_unicos2

array([0, 1, 2, 3, 4, 5, 6])

In [32]:
# En esta lección hemos aprendido algunos métodos de teórias de conjuntos. 
# Usando los arrays de elementos únicos obtenidos en el
#  ejercicio anterior realizad las siguientes operaciones:

# Elementos comunes entre los dos arrays
# Unión de los dos arrays

array_comun=np.intersect1d(valores_unicos1,valores_unicos2)
array_comun

array([0, 1, 2, 3, 4, 5, 6])

In [33]:
array_union=np.union1d(valores_unicos1,valores_unicos2)
array_union

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# ¿Qué elementos están en el array derivado de la distribución uniforme
#  y no en los únicos de la distribución binomial?
#  Extrae los valores númericos

np.setdiff1d()

In [ ]:
# ⚠️ Explicar cada uno de los outputs que os salgan. 
# Que significa cada una de estas operaciones que hemos ido extrayendo?



In [ ]:
# Cread dos arrays usando el método random.randint de Numpy
#  con 80 elementos cada uno con números del 1-100,
# con los siguientes nombres array1 y array2.



In [ ]:
# Extraed los valores únicos de cada uno de los arrays
#  y los guardáis en variables en las que se les llame array1 y array2.



In [ ]:
# Identificad los elementos presentes en el array1 pero no en el array2
#  y asiganarlo a una variable que se llame array3.



In [ ]:
# Identificad los elementos presentes en el array2 pero
#  no en el array1 y asiganarlo a una variable que se llame array4.



In [ ]:
# Identificad los elementos presentes en ambos arrays 
# y asiganarlos a una variable que se llame array5.



In [ ]:
# ¿Cuál es la relación que existe entre todos estos arrays? 
# 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.