In [ ]:
pairprogramming_numpy

In [ ]:
#1 Cread tres arrays: de una, dos y tres dimensiones. Lo podéis hacer usando los métodos de random que
# hemos aprendido o a través de listas em algunos casos. El array de 2 dimensiones debe ser de 2 filas y 3 columnas.
# El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [70]:
# Lo primero, importamos la librería:

import numpy as np

In [71]:
# Creamos los arrays según especificado:

array1 = np.random.randint((2, 3))
array2 = np.random.rand(3, 2)
array3 = np.random.random_sample((2, 3, 5))

In [74]:
# Comprobamos que las dimensiones son correctas:

print('Las dimensiones del array1 son', array1.ndim)
print('Las dimensiones del array2 son', array2.ndim)
print('Las dimensiones del array3 son', array3.ndim)

Las dimensiones del array1 son 1
Las dimensiones del array2 son 2
Las dimensiones del array3 son 3


In [75]:
# Chequead las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos
# devuelva las propiedades de una array que le pasemos.

In [77]:
def propiedades(nuestro_array):
    print(f'La forma de nuestro array es', nuestro_array.shape)
    print(f'El tamaño de nuestro array es', nuestro_array.size)
    print(f'La dimensión de nuestro array es', nuestro_array.ndim)
    print(f'El tipo de nuestro array es', nuestro_array.dtype)

In [78]:
propiedades(array3)

La forma de nuestro array es (2, 3, 5)
El tamaño de nuestro array es 30
La dimensión de nuestro array es 3
El tipo de nuestro array es float64


In [79]:
propiedades(array2)

La forma de nuestro array es (3, 2)
El tamaño de nuestro array es 6
La dimensión de nuestro array es 2
El tipo de nuestro array es float64


In [80]:
propiedades(array1)

La forma de nuestro array es (2,)
El tamaño de nuestro array es 2
La dimensión de nuestro array es 1
El tipo de nuestro array es int64


In [ ]:
# Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas.

In [81]:
array4 = np.identity(3)

In [46]:
# Printeamos el array para visualizarlo:

array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
propiedades(array4)

La forma de nuestro array es (3, 3)
El tamaño de nuestro array es 9
La dimensión de nuestro array es 2
El tipo de nuestro array es float64


In [83]:
# Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones
# creada en el primer ejercicio.

array5 = np.empty_like(array3)
array5

array([[[0.80844556, 0.51221168, 0.32483996, 0.31325266, 0.04873871],
        [0.14738931, 0.66601862, 0.86149357, 0.19682513, 0.24970169],
        [0.79430245, 0.1439508 , 0.65800688, 0.51143632, 0.15644102]],

       [[0.62423168, 0.77750732, 0.3143428 , 0.50827884, 0.23139559],
        [0.9742304 , 0.9070172 , 0.42101125, 0.93252248, 0.3530001 ],
        [0.8854443 , 0.15998441, 0.36186453, 0.47417082, 0.46961145]]])

In [84]:
propiedades(array3)

La forma de nuestro array es (2, 3, 5)
El tamaño de nuestro array es 30
La dimensión de nuestro array es 3
El tipo de nuestro array es float64


In [85]:
# Es el momento de hacer algunas operaciones entre arrays ¿Se puede sumar el array de dos dimensiones que creamos en el
# primer ejecicios a la matriz identidad? ¿Por qué?

In [52]:
np.add(array2, array4)

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [86]:
print('No se puede porque tienen formas distintas.')

No se puede porque tienen formas distintas.


In [54]:
propiedades(array2)

(3, 2)
6
2
float64


In [55]:
propiedades(array4)

(3, 3)
9
2
float64


In [87]:
# En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra.
# La solución puede ser crear un array nuevo.

# Creamos un array nuevo:

array5 = np.empty_like(array2)

In [59]:
array5

array([[0.09350696, 0.37173281],
       [0.70035775, 0.49270419],
       [0.89495668, 0.8109074 ]])

In [66]:
np.add(array2, array5)
(array2 + array5)

array([[0.91093016, 0.7678747 ],
       [1.40259113, 1.10179414],
       [1.47659405, 0.82003057]])

In [67]:
# Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

np.multiply(array2, array5)
(array2 * array5)

array([[0.07643476, 0.14725894],
       [0.49181459, 0.30010117],
       [0.52054025, 0.00739804]])

In [69]:
# Dividid las dos matrices

np.divide(array2, array5)
(array2 / array5)

array([[8.74184368, 1.065663  ],
       [1.0026781 , 1.2362183 ],
       [0.64990561, 0.01125056]])